### ISSUE TITLE
Color Palette

### ISSUE THREAD

**Issue by giobart** [nitindermohan/oak-new-docs#21]
Adding a draft page including:

- color palette
- reference to previous presentations 
- reference to drawings 
- fonts 
- font sizes
- link to cloud drawio

**Comment by nitindermohan** [comment]
Oakestra documentation reference diagram DrawIO: https://drive.google.com/file/d/1zfgXwXPI2Yb8G2N-U8Gd0xPaiQIe9R-2/view?usp=sharing
Please add color palettes, any icons and custom material you use so that we are consistent.

Also available in HackMD: https://hackmd.io/@oakestra/B17TSMwm1l
