### ISSUE TITLE
Update version to Bass

### ISSUE THREAD

**Issue by giobart** [nitindermohan/oak-new-docs#49]
<img width="582" alt="image" src="https://github.com/user-attachments/assets/06ca3d4e-e103-418d-b6e7-614c40a50779" />

Update version selector and banner to Oakestra Bass before release

**Comment by nitindermohan** [comment]
handled in https://github.com/nitindermohan/oak-new-docs/commit/5adb7f03adc10c8887e70994f7600a41459151cd
